linkedin/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/',include('user.urls'))
]

user/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.auth import views as auth_views
from . import views

urlpatterns = [
    path('',views.login_user,name='login'),
    path('registration',views.register,name='register'),
    path('homepage',views.homepage,name='homepage'),
    path('logout',views.logout_user, name='logout'),
]

user/models.py
from django.db import models
from django.contrib.postgres.fields import ArrayField
from django.contrib.auth.models import AbstractUser

class Job(models.Model):
    job_id=models.AutoField(primary_key=True)
    job_title=models.CharField(max_length=100)
    company_name=models.CharField(max_length=100)
    company_id=models.IntegerField()

class Education(models.Model):
    education_id=models.AutoField(primary_key=True)
    education_title=models.CharField(max_length=100)
    insitution_name=models.CharField(max_length=100)
    score=models.IntegerField()

class Comment(models.Model):
    comment_id=models.AutoField(primary_key=True)
    comment_text=models.TextField()
    post_id=models.IntegerField()

class Posts(models.Model):
    post_id=models.AutoField(primary_key=True)
    post_name=models.CharField(max_length=100)
    post_type=models.CharField(max_length=20)
    images=ArrayField(models.ImageField())
    comment_id=ArrayField(models.IntegerField())

class Skills(models.Model):
    skill_id=models.AutoField(primary_key=True)
    skill_name=models.CharField(max_length=30)

class User(AbstractUser):
    user_id=models.AutoField(primary_key=True)
    username = models.CharField(max_length=30,unique=True)
    first_name = models.CharField(max_length=30,blank=True,null=True)
    last_name = models.CharField(max_length=30,blank=True,null=True)
    email = models.EmailField(max_length=30,unique=True)
    password = models.CharField(max_length=100)
    date_of_birth = models.DateField(blank=True,null=True)
    profile_picture = models.ImageField(blank=True,null=True)
    headline = models.CharField(max_length=100,blank=True,null=True)
    summary = models.TextField(max_length=1000,blank=True,null=True)
    location = models.CharField(max_length=100)
    education_id=ArrayField(models.IntegerField(),blank=True,null=True)
    job_id=ArrayField(models.IntegerField(),blank=True,null=True)
    skill_id = ArrayField(models.IntegerField(),blank=True,null=True)

user/forms.py
from django import forms
from . models import User

class LoginForm(forms.Form):
    username= forms.CharField(max_length=100)
    password= forms.CharField(label='Password',widget=forms.PasswordInput)

class UserRegistrationForm(forms.ModelForm):
    password= forms.CharField(label='Password',widget=forms.PasswordInput)
    password2= forms.CharField(label='Repeat Password',widget=forms.PasswordInput)

    class Meta:
        model= User
        fields=('username','first_name','last_name','email')
    
    def clean_password2(self):
        cd=self.cleaned_data
        if cd['password'] != cd['password2']:
            raise forms.ValidationError('Passwords don\'t match.')
        return cd['password2']

user/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse,HttpResponseRedirect
from django.urls import reverse
from django.template import loader
from . models import User
from .forms import LoginForm, UserRegistrationForm
from django.contrib.auth import authenticate,login,logout
from django.contrib.auth.decorators import login_required

def login_user(request):
    if request.user.is_authenticated:
        return HttpResponseRedirect(reverse("homepage"))
    if request.method == "POST":
        form=LoginForm(request.POST)
        if form.is_valid():
            cd=form.cleaned_data
            user=authenticate(request,username=cd['username'],password=cd['password'])
            if user is not None:
                if user.is_active:
                    login(request,user)
                    return render(request,"user/homepage.html",{})
                else:
                    return HttpResponse("The user is not active")
            else:
                return HttpResponse("Invalid username or password")
    user_form=LoginForm()
    return render(request, "user/index.html",{"user_form": user_form})


def register(request):
    if request.user.is_authenticated:
        return HttpResponseRedirect(reverse("homepage"))
    if request.method == "POST":
        user_form = UserRegistrationForm(request.POST)
        print(user_form)
        if user_form.is_valid():
            new_user = user_form.save(commit=False)
            new_user.set_password(user_form.cleaned_data['password'])
            new_user.save()
            return render(request, "user/register_done.html",{"new_user":new_user})
    user_form=UserRegistrationForm()
    return render(request, "user/registration.html",{"user_form":user_form})

@login_required(login_url=login_user)
def homepage(request):
    if request.method == "POST":#creating a new post
        pass
    current_user = request.user
    print(current_user.user_id)
    return render(request,"user/homepage.html",{})

@login_required(login_url=login_user)
def logout_user(request):
    logout(request)
    return redirect('login')

user/templates/user/homepage.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <title>LinkedIn Profile</title>
    <link rel="stylesheet" href="{% static 'login/homepage.css' %}">
</head>
<body>
  <nav class="navbar">
    <div class="navbar-container">
        <a class="navbar-logo" href="#">LinkedIn</a>
        <ul class="navbar-menu">
        <li><a href="#">Articles</a></li>
        <li><a href="#">People</a></li>
        <li><a href="#">Jobs</a></li>
        <li><a href={% url 'logout' %}>Logout</a></li>
        </ul>
    </div>
</nav>
<div class="main-container">
    <div class="profile">
      <img src="{% static 'images/base_wall.jpeg' %}" class="im">
      <div class="profile-head">
        <div class="profile-picture"></div>
          <h1>{{ user.first_name }} {{ user.last_name }}</h1>
          <h3>{{ user.headline }}</h3>
          <p>{{ user.location }}</p>
          <p>{{ user.summary }}</p>
      </div>
    </div>

    <div class="details-container">
        <h2>Experience</h2>
        {% for experience in user.experiences %}
            <h4>{{ experience.title }}</h4>
            <p>{{ experience.company }}</p>
            <p>{{ experience.start_date }} - {{ experience.end_date }}</p>
            <p>{{ experience.description }}</p>
        {% empty %}
            <p>No experiences to display.</p>
        {% endfor %}
    </div>

    <div class="details-container">
        <h2>Education</h2>
        {% for education in user.educations %}
            <h4>{{ education.degree }}</h4>
            <p>{{ education.school }}</p>
            <p>{{ education.start_date }} - {{ education.end_date }}</p>
            <p>{{ education.field_of_study }}</p>
        {% empty %}
            <p>No education information available.</p>
        {% endfor %}
    </div>

    <div class="details-container">
        <h2>Skills</h2>
        <ul>
            {% for skill in user.skills %}
                <li>{{ skill }}</li>
            {% empty %}
                <p>No skills to display.</p>
            {% endfor %}
        </ul>
    </div>

    <div class="details-container">
        <h2>Projects</h2>
        {% for project in user.projects %}
            <h4>{{ project.title }}</h4>
            <p>{{ project.description }}</p>
        {% empty %}
            <p>No projects to display.</p>
        {% endfor %}
    </div>
  </div>
</body>
</html>

user/templates/user/index.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
  <title>Registration</title>
  <link rel="stylesheet" type="text/css" href="{% static 'login/register.css' %}">
</head>
<body>
    <nav class="navbar">
        <div class="navbar-container">
            <a class="navbar-logo" href="#">LinkedIn</a>
            <ul class="navbar-menu">
            <li><a href="#">Articles</a></li>
            <li><a href="#">People</a></li>
            <li><a href="#">Jobs</a></li>
            <li><a href={% url 'register' %}>Register</a></li>
            </ul>
        </div>
    </nav>
  <div class="main-container">
    <div class="container">
      <h2>Login</h2>
      <form method="post">
        {% csrf_token %}
        <div class="form-group">
          <label for="id_username">Username:</label>
          {{ user_form.username }}
          {% for error in form.username.errors %}
            <p class="error">{{ error }}</p>
          {% endfor %}
        </div>
        <div class="form-group">
          <label for="id_password">Password:</label>
          {{ user_form.password }}
          {% for error in form.password.errors %}
            <p class="error">{{ error }}</p>
          {% endfor %}
        </div>
        <button type="submit">Login</button>
      </form>
    </div>
  </div>
</body>
</html>

user/templates/user/register_done.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Congrats {{new_user.username}} account succesfully created</h1>
</body>
</html>

user/templates/user/registration.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
  <title>Registration</title>
  <link rel="stylesheet" type="text/css" href="{% static 'login/register.css' %}">
</head>
<body>
    <nav class="navbar">
        <div class="navbar-container">
            <img class="navbar-logo" href="{% static 'images/logo.png' %}">
            <ul class="navbar-menu">
            <li><a href="#">Articles</a></li>
            <li><a href="#">People</a></li>
            <li><a href="#">Jobs</a></li>
            <li><a href={% url 'login' %}>Sign In</a></li>
            </ul>
        </div>
    </nav>
    <div class="main-container">
  <div class="container">
    <h2>Welcome to LinkedIn</h2>
    <form method="post">
      {% csrf_token %}
      <div class="form-group">
        <label for="id_username">Username:</label>
        {{ user_form.username }}
        {% for error in form.username.errors %}
          <p class="error">{{ error }}</p>
        {% endfor %}
      </div>
      <div class="form-group">
        <label for="id_first_name">First Name:</label>
        {{ user_form.first_name }}
        {% for error in form.first_name.errors %}
          <p class="error">{{ error }}</p>
        {% endfor %}
      </div>
      <div class="form-group">
        <label for="id_last_name">Last Name:</label>
        {{ user_form.last_name }}
        {% for error in form.last_name.errors %}
          <p class="error">{{ error }}</p>
        {% endfor %}
      </div>
      <div class="form-group">
        <label for="id_email">Email:</label>
        {{ user_form.email }}
        {% for error in form.email.errors %}
          <p class="error">{{ error }}</p>
        {% endfor %}
      </div>
      <div class="form-group">
        <label for="id_password">Password:</label>
        {{ user_form.password }}
        {% for error in form.password.errors %}
          <p class="error">{{ error }}</p>
        {% endfor %}
      </div>
      <div class="form-group">
        <label for="id_password2">Repeat Password:</label>
        {{ user_form.password2 }}
        {% for error in form.password2.errors %}
          <p class="error">{{ error }}</p>
        {% endfor %}
      </div>
      <button type="submit">Register</button>
    </form>
  </div>
</div>
</body>
</html>